[project]
name = "backend"
version = "0.1.0"
description = "The CORS proxy backend for the humble vault."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ipython>=9.2.0",
]
